# Generated by Django 5.0.4 on 2024-05-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_member_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/'),
        ),
    ]
